validate start time on reservation request
rigetti/qcs-cli pull request #11
Opened 2019-08-02 18:51 UTC by erichulburd

2019-08-05 17:59 UTC, cbosborn requested changes
@erichulburd Also looks good, but hold off for a bit on merging. Curious specifically, what's the purpose of this PR?

2019-08-05 17:59 UTC, cbosborn commented on src/utils.ts
> +    throw new Error(`Must use a date a future to make availability request. Received ${startMoment.toISOString()}.`);
" ... *in the future to make ..."

2019-08-05 17:59 UTC, cbosborn commented on src/utils.ts
> +  const permitOffset = moment.duration(1, 'minute');
Are you adding 1 minute to ensure that "now" is effectively in the future?

2019-08-05 17:59 UTC, cbosborn commented on test/reserve.test.ts
> +      expect(err.message).to.include('Must use a date a future to make availability request');
Same here, "... *in the future ..." unless I'm misreading this.

2019-08-06 23:57 UTC, erichulburd commented
@cbosborn There was a bit of confusion last week with somebody trying to reserve a time in the past and Celena mentioned it'd be nice to get a user friendly error message when that happens.

I can include a force flag to accommodate users when trying to reserve in the past.

2019-08-07 23:37 UTC, erichulburd commented
Don't need in this in qcs-cli

2019-08-07 23:37 UTC, closed without merging